index:
  - /
catalog:
  - /product/:product_by_slug
  - /brand/:products_by_brand_slug
  - /brand/:products_by_brand_slug/product/:product_by_slug
  - /category/:products_by_category_slug
  - /category/:products_by_category_slug/product/:product_by_slug
  - /department/:products_by_department_slug
  - /department/:products_by_department_slug/brand/:products_by_brand_slug
  - /department/:products_by_department_slug/category/:products_by_category_slug
  - /department/:products_by_department_slug/product/:product_by_slug
  - /department/:products_by_department_slug/brand/:products_by_brand_slug/product/:product_by_slug
  - /department/:products_by_department_slug/category/:products_by_category_slug/product/:product_by_slug
search:
  - /search
